### Case Study 2:
Load practice.csv file as a data-frame and perform following operations on the data-frame

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df= pd.read_csv('practice.csv')
df

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure
0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,No
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Gd
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,No
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Av
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,No
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,No
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,No
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,NaN
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Av
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,No
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No

1.	Display all columns

In [5]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotArea', 'LotShape', 'LotConfig',
       'LandSlope', 'OverallQual', 'YearBuilt', 'MasVnrArea', 'ExterQual',
       'BsmtExposure'],
      dtype='object')

2.	create numerical and categorical columns list

In [10]:
df.select_dtypes(include='number').head()

   MSSubClass  LotArea  OverallQual  YearBuilt  MasVnrArea
0          60     8450            7       2003         196
1          20     9600            6       1976           0
2          60    11250            7       2001         162
3          70     9550            7       1915           0
4          60    14260            8       2000         350

In [12]:
df.select_dtypes(include='object').head()

  MSZoning LotShape LotConfig LandSlope ExterQual BsmtExposure
0       RL      Reg    Inside       Gtl        Gd           No
1       RL      Reg       FR2       Gtl        TA           Gd
2       RL      IR1    Inside       Gtl        Gd           Mn
3       RL      IR1    Corner       Gtl        TA           No
4       RL      IR1       FR2       Gtl        Gd           Av

3.	display size of the data-frame

In [13]:
df.shape

(30, 11)

4.	rename column MSSubClass -> SubClass, MSZoning -> Zones

In [70]:
df.rename(columns={'MSSubClass':'SubClass','MSZoning':'Zones'})

,SubClass,Zones,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,col_value
0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,No,RL
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Gd,RL
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn,RL
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,No,RL
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Av,RL
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No,RL
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av,RL
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn,RL
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No,RM
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,No,RL
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No,RL
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No,RL
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No,RL
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av,RL
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,No,RL
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No,RM
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,No,RL
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,None,RL
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No,RL
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No,RL
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Av,RL
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No,RM
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No,RL
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No,RM
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn,RL
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,No,RL
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn,RL
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No,RL
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd,RL
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No,RM

5.	display distinct values for Zoning, LotShape, LotConfig

In [81]:
column_values = df[["MSZoning","LotShape","LotConfig"]].values. ravel()
unv = pd.unique(column_values)
print(unv)

['RL' 'Reg' 'Inside' 'FR2' 'IR1' 'Corner' 'RM' 'IR2' 'CulDSac']

6.	display count of distinct values for Zoning, LotShape, LotConfig

In [72]:
df[["MSZoning","LotShape","LotConfig"]].nunique()

MSZoning     2
LotShape     3
LotConfig    4
dtype: int64

7.	max, min of column YearBuilt

In [82]:
df.YearBuilt.max()

2007

In [83]:
df.YearBuilt.min()

1915

8.	create a new column “year_diff’. This will be holding difference of current year and YearBuilt

In [89]:
from datetime import datetime
df['year_diff']= datetime.today().year - df.YearBuilt
df

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,col_value,year_diff
0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,No,RL,18
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Gd,RL,45
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn,RL,20
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,No,RL,106
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Av,RL,21
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No,RL,28
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av,RL,17
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn,RL,48
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No,RM,90
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,No,RL,82
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No,RL,56
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No,RL,16
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No,RL,59
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av,RL,15
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,No,RL,61
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No,RM,92
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,No,RL,51
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,None,RL,54
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No,RL,17
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No,RL,63
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Av,RL,16
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No,RM,91
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No,RL,19
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No,RM,45
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn,RL,53
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,No,RL,14
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn,RL,70
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No,RL,14
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd,RL,64
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No,RM,94

9.	display distinct MSZoning for each OverallQual

In [91]:
df.groupby('OverallQual')['MSZoning'].unique()

OverallQual
4    [RL, RM]
5    [RL, RM]
6        [RL]
7    [RL, RM]
8        [RL]
9        [RL]
Name: MSZoning, dtype: object

10.	What is the maximum LotArea where  BsmtExposure = Mn?

In [118]:
##df.groupby('BsmtExposure')['LotArea'].max()
df[df.BsmtExposure == 'Mn']['LotArea'].max()

16321

11.	Sort dataframe based on following columns and orders: MSSubClass; ascending, YearBuilt; descending

In [120]:
df.sort_values(by=['MSSubClass'],ascending=True , inplace=False)

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,col_value,year_diff
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,Mn,RL,61
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Mn,RL,45
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,Mn,RL,14
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn,RL,70
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,Mn,RL,14
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn,RL,53
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Mn,RL,17
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,Mn,RL,19
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,Mn,RL,63
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,Mn,RL,17
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,Mn,RL,56
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,Mn,RL,51
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,Mn,RL,59
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Mn,RL,15
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Mn,RL,64
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,Mn,RM,94
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,Mn,RM,91
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,Mn,RM,92
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,Mn,RM,90
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,Mn,RL,28
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,Mn,RL,16
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Mn,RL,16
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn,RL,48
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Mn,RL,21
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn,RL,20
0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,Mn,RL,18
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,Mn,RL,106
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,Mn,RL,54
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,Mn,RM,45
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,Mn,RL,82

In [121]:
df.sort_values(by=['YearBuilt'],ascending=False , inplace=False)

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,col_value,year_diff
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,Mn,RL,14
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,Mn,RL,14
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Mn,RL,15
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,Mn,RL,16
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Mn,RL,16
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,Mn,RL,17
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Mn,RL,17
0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,Mn,RL,18
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,Mn,RL,19
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn,RL,20
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Mn,RL,21
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,Mn,RL,28
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,Mn,RM,45
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Mn,RL,45
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn,RL,48
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,Mn,RL,51
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn,RL,53
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,Mn,RL,54
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,Mn,RL,56
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,Mn,RL,59
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,Mn,RL,61
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,Mn,RL,63
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Mn,RL,64
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn,RL,70
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,Mn,RL,82
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,Mn,RM,90
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,Mn,RM,91
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,Mn,RM,92
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,Mn,RM,94
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,Mn,RL,106

12.	What is average OverallQual.

In [122]:
df. OverallQual.mean()

6.3

13.	convert column ‘YearBuilt’ into date type.

In [128]:
#df.select_dtypes(include='date')

df['YearBuilt'] = pd.to_datetime(df['YearBuilt'])
df.dtypes

MSSubClass               int64
MSZoning                object
LotArea                  int64
LotShape                object
LotConfig               object
LandSlope               object
OverallQual              int64
YearBuilt       datetime64[ns]
MasVnrArea               int64
ExterQual               object
BsmtExposure            object
col_value               object
year_diff                int64
dtype: object

14.	Group by YearBuilt and find maximum OverallQal

In [132]:
df.groupby('OverallQual')['YearBuilt'].max()

OverallQual
4   1970-01-01 00:00:00.000001967
5   1970-01-01 00:00:00.000002004
6   1970-01-01 00:00:00.000001976
7   1970-01-01 00:00:00.000002006
8   1970-01-01 00:00:00.000002007
9   1970-01-01 00:00:00.000002005
Name: YearBuilt, dtype: datetime64[ns]

15.	Load the practice.csv again with MSSubClass as new index

In [143]:
df1= pd.read_csv('practice.csv')
df1.set_index('MSSubClass')

,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure
MSSubClass,,,,,,,,,,
60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,No
20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Gd
60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn
70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,No
60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Av
50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No
20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av
60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn
50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No
190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,No
20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No
60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No
20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No
20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av
20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,No
45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No
20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,No
90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,NaN
20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No
20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No
60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Av
45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No
20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No
120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No
20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn
20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,No
20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn
20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No
20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd
30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No

16.	Convert LotArea as numpy array

In [147]:
df.LotArea.to_numpy()

array([ 8450,  9600, 11250,  9550, 14260, 14115, 10084, 10382,  6120,
        7420, 11200, 11924, 12968, 10652, 10920,  6120, 11241, 10791,
       13695,  7560, 14215,  7449,  9742,  4224,  8246, 14230,  7200,
       11478, 16321,  6324], dtype=int64)

17.	In column MasVnrArea replace 0 with -1

In [164]:
df['MasVnrArea']= df.replace('0','-1')


df["MasVnrArea"].replace({"0":"-1"} ,inplace=True)
df

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,col_value,year_diff
0,60,RL,8450,Reg,Inside,Gtl,7,1970-01-01 00:00:00.000002003,60,Gd,Mn,RL,18
1,20,RL,9600,Reg,FR2,Gtl,6,1970-01-01 00:00:00.000001976,20,TA,Mn,RL,45
2,60,RL,11250,IR1,Inside,Gtl,7,1970-01-01 00:00:00.000002001,60,Gd,Mn,RL,20
3,70,RL,9550,IR1,Corner,Gtl,7,1970-01-01 00:00:00.000001915,70,TA,Mn,RL,106
4,60,RL,14260,IR1,FR2,Gtl,8,1970-01-01 00:00:00.000002000,60,Gd,Mn,RL,21
5,50,RL,14115,IR1,Inside,Gtl,5,1970-01-01 00:00:00.000001993,50,TA,Mn,RL,28
6,20,RL,10084,Reg,Inside,Gtl,8,1970-01-01 00:00:00.000002004,20,Gd,Mn,RL,17
7,60,RL,10382,IR1,Corner,Gtl,7,1970-01-01 00:00:00.000001973,60,TA,Mn,RL,48
8,50,RM,6120,Reg,Inside,Gtl,7,1970-01-01 00:00:00.000001931,50,TA,Mn,RM,90
9,190,RL,7420,Reg,Corner,Gtl,5,1970-01-01 00:00:00.000001939,190,TA,Mn,RL,82
10,20,RL,11200,Reg,Inside,Gtl,5,1970-01-01 00:00:00.000001965,20,TA,Mn,RL,56
11,60,RL,11924,IR1,Inside,Gtl,9,1970-01-01 00:00:00.000002005,60,Ex,Mn,RL,16
12,20,RL,12968,IR2,Inside,Gtl,5,1970-01-01 00:00:00.000001962,20,TA,Mn,RL,59
13,20,RL,10652,IR1,Inside,Gtl,7,1970-01-01 00:00:00.000002006,20,Gd,Mn,RL,15
14,20,RL,10920,IR1,Corner,Gtl,6,1970-01-01 00:00:00.000001960,20,TA,Mn,RL,61
15,45,RM,6120,Reg,Corner,Gtl,7,1970-01-01 00:00:00.000001929,45,TA,Mn,RM,92
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970-01-01 00:00:00.000001970,20,TA,Mn,RL,51
17,90,RL,10791,Reg,Inside,Gtl,4,1970-01-01 00:00:00.000001967,90,TA,Mn,RL,54
18,20,RL,13695,Reg,Inside,Gtl,5,1970-01-01 00:00:00.000002004,20,TA,Mn,RL,17
19,20,RL,7560,Reg,Inside,Gtl,5,1970-01-01 00:00:00.000001958,20,TA,Mn,RL,63
20,60,RL,14215,IR1,Corner,Gtl,8,1970-01-01 00:00:00.000002005,60,Gd,Mn,RL,16
21,45,RM,7449,Reg,Inside,Gtl,7,1970-01-01 00:00:00.000001930,45,TA,Mn,RM,91
22,20,RL,9742,Reg,Inside,Gtl,8,1970-01-01 00:00:00.000002002,20,Gd,Mn,RL,19
23,120,RM,4224,Reg,Inside,Gtl,5,1970-01-01 00:00:00.000001976,120,TA,Mn,RM,45
24,20,RL,8246,IR1,Inside,Gtl,5,1970-01-01 00:00:00.000001968,20,TA,Mn,RL,53
25,20,RL,14230,Reg,Corner,Gtl,8,1970-01-01 00:00:00.000002007,20,Gd,Mn,RL,14
26,20,RL,7200,Reg,Corner,Gtl,5,1970-01-01 00:00:00.000001951,20,TA,Mn,RL,70
27,20,RL,11478,Reg,Inside,Gtl,8,1970-01-01 00:00:00.000002007,20,Gd,Mn,RL,14
28,20,RL,16321,IR1,CulDSac,Gtl,5,1970-01-01 00:00:00.000001957,20,TA,Mn,RL,64
29,30,RM,6324,IR1,Inside,Gtl,4,1970-01-01 00:00:00.000001927,30,TA,Mn,RM,94

18.	Check if there is/are any Null values (NaN) in the data given

In [168]:
count = df.isnull().sum()
per = df.isnull().sum()
pd.concat([pd.DataFrame(count, columns=['count'])], axis = 1)

              count
MSSubClass        0
MSZoning          0
LotArea           0
LotShape          0
LotConfig         0
LandSlope         0
OverallQual       0
YearBuilt         0
MasVnrArea        0
ExterQual         0
BsmtExposure      0
col_value         0
year_diff         0

19.	Display percentage of missing values in each column if any

In [169]:
count = df.isnull().sum()
per = df.isnull().sum()/df.shape[0]*100
pd.concat([pd.DataFrame(count, columns=['count']),pd.DataFrame(per, columns=['percentage']) ], axis = 1).sort_values('percentage')

              count  percentage
MSSubClass        0         0.0
MSZoning          0         0.0
LotArea           0         0.0
LotShape          0         0.0
LotConfig         0         0.0
LandSlope         0         0.0
OverallQual       0         0.0
YearBuilt         0         0.0
MasVnrArea        0         0.0
ExterQual         0         0.0
BsmtExposure      0         0.0
col_value         0         0.0
year_diff         0         0.0

20.	Select records where LotConfig is Inside

In [174]:
df[['LotConfig']]=='Inside'

    LotConfig
0        True
1       False
2        True
3       False
4       False
5        True
6        True
7       False
8        True
9       False
10       True
11       True
12       True
13       True
14      False
15      False
16      False
17       True
18       True
19       True
20      False
21       True
22       True
23       True
24       True
25      False
26      False
27       True
28      False
29       True

21.	Make a new dataframe with only numeric columns

In [176]:
df.select_dtypes(include='number')

    LotArea  OverallQual  MasVnrArea  year_diff
0      8450            7          60         18
1      9600            6          20         45
2     11250            7          60         20
3      9550            7          70        106
4     14260            8          60         21
5     14115            5          50         28
6     10084            8          20         17
7     10382            7          60         48
8      6120            7          50         90
9      7420            5         190         82
10    11200            5          20         56
11    11924            9          60         16
12    12968            5          20         59
13    10652            7          20         15
14    10920            6          20         61
15     6120            7          45         92
16    11241            6          20         51
17    10791            4          90         54
18    13695            5          20         17
19     7560            5          20         63
20    14215            8          60         16
21     7449            7          45         91
22     9742            8          20         19
23     4224            5         120         45
24     8246            5          20         53
25    14230            8          20         14
26     7200            5          20         70
27    11478            8          20         14
28    16321            5          20         64
29     6324            4          30         94

22.	Make a new dataframe with only factorial/string columns

In [179]:
df.select_dtypes(include='object')

,MSSubClass,MSZoning,LotShape,LotConfig,LandSlope,ExterQual,BsmtExposure,col_value
0,60,RL,Reg,Inside,Gtl,Gd,Mn,RL
1,20,RL,Reg,FR2,Gtl,TA,Mn,RL
2,60,RL,IR1,Inside,Gtl,Gd,Mn,RL
3,70,RL,IR1,Corner,Gtl,TA,Mn,RL
4,60,RL,IR1,FR2,Gtl,Gd,Mn,RL
5,50,RL,IR1,Inside,Gtl,TA,Mn,RL
6,20,RL,Reg,Inside,Gtl,Gd,Mn,RL
7,60,RL,IR1,Corner,Gtl,TA,Mn,RL
8,50,RM,Reg,Inside,Gtl,TA,Mn,RM
9,190,RL,Reg,Corner,Gtl,TA,Mn,RL
10,20,RL,Reg,Inside,Gtl,TA,Mn,RL
11,60,RL,IR1,Inside,Gtl,Ex,Mn,RL
12,20,RL,IR2,Inside,Gtl,TA,Mn,RL
13,20,RL,IR1,Inside,Gtl,Gd,Mn,RL
14,20,RL,IR1,Corner,Gtl,TA,Mn,RL
15,45,RM,Reg,Corner,Gtl,TA,Mn,RM
16,20,RL,IR1,CulDSac,Gtl,TA,Mn,RL
17,90,RL,Reg,Inside,Gtl,TA,Mn,RL
18,20,RL,Reg,Inside,Gtl,TA,Mn,RL
19,20,RL,Reg,Inside,Gtl,TA,Mn,RL
20,60,RL,IR1,Corner,Gtl,Gd,Mn,RL
21,45,RM,Reg,Inside,Gtl,TA,Mn,RM
22,20,RL,Reg,Inside,Gtl,Gd,Mn,RL
23,120,RM,Reg,Inside,Gtl,TA,Mn,RM
24,20,RL,IR1,Inside,Gtl,TA,Mn,RL
25,20,RL,Reg,Corner,Gtl,Gd,Mn,RL
26,20,RL,Reg,Corner,Gtl,TA,Mn,RL
27,20,RL,Reg,Inside,Gtl,Gd,Mn,RL
28,20,RL,IR1,CulDSac,Gtl,TA,Mn,RL
29,30,RM,IR1,Inside,Gtl,TA,Mn,RM

23.	Drop column ExterQual

In [188]:
df.drop('ExterQual', axis=1, inplace=True)--- deketed

KeyError: "['ExterQual'] not found in axis"

24.	Group data on LotShape and find average LotArea

In [190]:
df.groupby('LotShape')['LotArea'].mean()

LotShape
IR1    11492.307692
IR2    12968.000000
Reg     9085.187500
Name: LotArea, dtype: float64

25.	Write code to get a pivot table as shown (average of MSSubClass)